import { Navbar } from '@/components/navbar'
import { validateRequest } from '@/lib/auth'
import SessionProvider from '@/providers/session-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Providers } from './providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    const session = await validateRequest()
    return (
        <html lang='en'>
            <body className={inter.className}>
                <Providers>
                    <SessionProvider value={session}>
                        <Navbar />
                        {children}
                    </SessionProvider>
                </Providers>
            </body>
        </html>
    )
}
